---
# tasks file for Ubuntu 14.04 Trusty
- name: Install Mono runtime, mcs and xsp4
  apt: pkg={{ item }} state=present state=build-dep
  with_items:
     - mono-runtime
     - mono-mcs
     - mono-xsp4
